version: '3.8'

services:
  azure-cli-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azure-cli-mcp
    environment:
      - AZURE_CREDENTIALS=${AZURE_CREDENTIALS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-azure-cli-mcp}
      - MCP_SERVER_VERSION=${MCP_SERVER_VERSION:-1.0.0}
    stdin_open: true
    tty: true
    volumes:
      # Mount for development (optional)
      - ./azure_cli_mcp:/app/azure_cli_mcp
      # Mount for logs (optional)
      - ./logs:/app/logs
    networks:
      - mcp-network
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import azure_cli_mcp; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  mcp-network:
    driver: bridge

volumes:
  logs:
    driver: local 